---
# tasks file for nginx
- name: Start Nginx
  service: name=nginx state=started

- name: Copy FruitBreedomics configuration file
  copy: src=fruitbreedomics.conf dest=/etc/nginx/default.d owner=root group=root
  notify: Reload Nginx
  tags: ['configure']
