---
- hosts: fruitbreedomics
  roles:
    # install with: ansible-galaxy install andrewsomething.do-agent
    - role: andrewsomething.do-agent
      tags: do-agent
    - packages


# Associate further roles to servers in specific group in this file...

...
