---
- hosts: fruitbreedomics
  roles:
    # install with: ansible-galaxy install andrewsomething.do-agent
    - role: andrewsomething.do-agent
      tags: do-agent
    - volume
    - packages
    - role: andrewrothstein.miniconda
      tags: miniconda
    - role: openvz
      tags: openvz_role


# Associate further roles to servers in specific group in this file...

...
