---
# tasks file for volume
- name: Mount up device by UUID
  mount:
    path: /mnt/fb_volume
    src: /dev/disk/by-id/scsi-0DO_Volume_fb-volume
    fstype: ext4
    opts: defaults,nofail,discard
    state: mounted
  tags: volume
