---
# tasks file for volume
- name: Mount up device by UUID
  mount:
    path: /mnt/fb_volume
    src: /dev/disk/by-id/scsi-0DO_Volume_fb-volume
    fstype: xfs
    opts: discard,defaults,noatime
    state: mounted
  tags: volume
