---
# handlers file for openvz
- name: restart iptables
  service: name=iptables state=restarted

- name: move_openvz_files
  shell: 'mv /vz/* {{container_files_dir}} ; rmdir /vz;  ln -s {{container_files_dir}} /vz'

- name: Reboot machine for changes to take effect
  shell: shutdown -r now
